add pattern fail check, add success conditional to downstream job

diff --git a/.github/workflows/match-ref.yml b/.github/workflows/match-ref.yml
--- a/.github/workflows/match-ref.yml
+++ b/.github/workflows/match-ref.yml
@@ -15,9 +15,16 @@ jobs:
           pattern: ${{vars.REF_PATTERN}}
           target: ${{github.head_ref||github.ref}}
 
+      - if: ${{ '' == steps.name.outputs.value || failure() }}
+        name: fail empty pattern match
+        run: |
+          echo "pattern match failed" >> $GITHUB_STEP_SUMMARY
+          exit 1
+
   validate:
     runs-on: ubuntu-latest
     needs: environment
+    if: ${{ success() }}
     environment:
       name: ${{needs.environment.outputs.name}}
     steps:
